export {
  canReadStudentProfile,
  canReadRestrictedContact,
  assignedStudentIds,
  isAssignedToClass,
  assignedClassIds,
  classStudentIdsAsOf,
  guardianChildIds,
  canListAllStudents,
  canManageStudents,
  canManageAcademicStructure,
  canReadAcademicStructure,
} from "./students-access.js";

export { assertPermission, assertAnyPermission, notFound } from "./permissions.js";

export {
  ADMISSIONS_READ_PERMISSIONS,
  canReadAdmissions,
  canManageEnquiries,
  canManageApplications,
  canManageOffers,
  canDecideAdmissions,
  canConvertAdmissions,
  canReadAdmissionsForms,
  canManageAdmissionsForms,
  canReadAdmissionsCampaigns,
  canManageAdmissionsCampaigns,
  canReadPublicSubmissions,
  allowedApplicationTransitions,
  isApplicationStatusTransitionAllowed,
  transitionRequiresDecide,
  assertApplicationStatusTransition,
  createInboxNotification,
  auditAdmissions,
} from "./admissions.js";

export { AppError, pgErrorToAppError, type AppErrorDetails } from "./errors.js";

export {
  normalizePlatformDomain,
  parseHostHeader,
  selectRequestHost,
  firstForwardedHost,
  classifyHostname,
  publicHostKindFromClassification,
  classifyPublicHost,
  loginHostKindFromRequest,
  schoolPublicHostname,
  schoolPublicOrigin,
  schoolInviteUrl,
  originForHostname,
  formatHostname,
  type ParsedHost,
  type HostClassification,
  type PublicHostKind,
  type LoginHostKind,
} from "./hostname.js";

export {
  bindOrganisationHint,
  headerMatchesHostSlug,
  type BoundOrganisation,
} from "./tenancy.js";

export {
  writeAudit,
  currentAcademicYear,
  endDatedRow,
  isoDate,
} from "./academic.js";

export {
  countForeignKeyUsage,
  deleteConfigOnlyYearGroupLinks,
  deletionBlockedError,
  includeArchivedRequested,
  loadAcademicLifecycle,
  type AcademicEntityKind,
} from "./academic-lifecycle.js";

export {
  comingLater,
  PORTAL_STUDENT_SQL,
  mapPortalStudent,
  portalChildSummary,
  loadSchool,
  loadPortalStudentsByIds,
  loadPortalStudent,
  loadOwnStudentProfile,
  requireLinkedChild,
  loadViewerGuardianship,
  PARENT_CHILD_SECTIONS,
  STUDENT_DASHBOARD_SECTIONS,
} from "./portal.js";

export {
  mapNotification,
  listInboxNotifications,
  countUnreadNotifications,
  markNotificationRead,
} from "./notifications.js";

export {
  isAttendanceCategory,
  roundAttendancePercentage,
  attendancePercentage,
  summariseAttendanceMarks,
  emptyAttendanceSummary,
  type AttendanceSummary,
} from "./attendance.js";

export {
  resolveStudentPortalAccess,
  yearGroupPortalEffective,
  type StudentPortalPolicyInput,
  type StudentPortalDecision,
} from "./student-portal.js";

export {
  ATTENDANCE_SCHOOL_READ_PERMISSIONS,
  ATTENDANCE_REGISTER_PERMISSIONS,
  canReadSchoolAttendance,
  canManageSchoolAttendance,
  canCorrectAttendance,
  canManageAssignedAttendance,
  canManageAttendanceConfig,
  canReadOwnChildrenAttendance,
  canReadOwnAttendance,
  assertCanAccessRegister,
  assertCanReadStudentAttendance,
  loadStudentPortalDecision,
  requireStudentPortalEnabled,
  studentDocumentVisibleToAudience,
  buildStudentDocumentKey,
} from "./attendance-access.js";

export {
  isLearningAssignmentStatus,
  isLearningSubmissionStatus,
  isLearningTargetType,
  isLearningResourceKind,
  isLearningWorkTypeKey,
  isLearningStudentBucket,
  isAssignmentStatusTransitionAllowed,
  isSubmissionStatusTransitionAllowed,
  pupilCanSubmitFrom,
  pupilCanSaveDraftFrom,
  pupilCanWriteOnAssignment,
  isAllowedLearningUrl,
  isScoreInRange,
  summariseLearningProgress,
  isLearningVisibleToPupil,
  isLearningAssignedForNotification,
  studentLearningBuckets,
  parentLearningStatus,
  learningNotificationBody,
  type LearningProgressCounts,
  type StudentLearningVisibilityInput,
} from "./learning.js";

export {
  LMS_SCHOOL_READ_PERMISSIONS,
  LMS_ASSIGN_PERMISSIONS,
  LMS_READ_WORK_PERMISSIONS,
  LMS_READ_SUBMISSION_PERMISSIONS,
  LMS_MARK_PERMISSIONS,
  canManageSchoolLearning,
  canReadSchoolLearning,
  canManageAssignedLearning,
  canReadAssignedLearning,
  canMarkSchoolLearning,
  canMarkAssignedLearning,
  canReadOwnChildrenLearning,
  canReadOwnLearning,
  assertCanManageLearningWork,
  assertCanAccessClassForLearning,
  assertCanTargetClass,
  assertCanTargetStudent,
  assertCanTargetYearGroup,
  assertCanSetIntendedYearGroup,
  assertCanAssignSubject,
  loadAuthorisedLearningClassIds,
  loadAuthorisedLearningYearGroupIds,
  loadAuthorisedLearningSubjectIds,
  loadAuthorisedLearningStudentIds,
  assertCanReadAssignment,
  assertCanManageAssignment,
  assertCanReadOrMarkSubmission,
  canSeeLearningRecipient,
  resolveTargetRecipients,
  snapshotAssignmentRecipients,
  notifyLearningAssigned,
  notifyLearningFeedback,
  buildLearningResourceKey,
  buildSubmissionAttachmentKey,
} from "./learning-access.js";

export {
  loadTeacherAcademicScope,
  loadScopedTeachingClasses,
  actorHasSchoolWideTeachingScope,
  assertClassInTeacherScope,
  assertYearGroupInTeacherScope,
  assertSubjectInTeacherScope,
  type TeacherAcademicScope,
} from "./teacher-scope.js";

export {
  isFormalAssessmentStatus,
  isFormalAssessmentTypeKey,
  isGradeSchemeKind,
  isResultReviewStatus,
  isReportingPeriodStatus,
  isAcademicReportStatus,
  isAssessmentStatusTransitionAllowed,
  isReportStatusTransitionAllowed,
  canEnterResultsOnAssessment,
  isFormalResultVisibleToAudience,
  isScoreWithinMaximum,
  computePercentage,
  summariseSubjectProgress,
  summariseAssessmentResults,
  academicNotificationBody,
  type ProgressPoint,
  type SubjectProgressSummary,
} from "./assessments.js";

export {
  ASSESSMENT_SCHOOL_READ_PERMISSIONS,
  ASSESSMENT_MANAGE_PERMISSIONS,
  ASSESSMENT_READ_PERMISSIONS,
  RESULT_SCHOOL_READ_PERMISSIONS,
  RESULT_ENTER_PERMISSIONS,
  RESULT_READ_PERMISSIONS,
  REPORT_SCHOOL_READ_PERMISSIONS,
  REPORT_MANAGE_PERMISSIONS,
  REPORT_READ_PERMISSIONS,
  canReadSchoolAssessments,
  canManageSchoolAssessments,
  canReadSchoolResults,
  canEnterSchoolResults,
  canReviewResults,
  canPublishResults,
  canReadSchoolReports,
  canManageSchoolReports,
  canReviewReports,
  canPublishReports,
  loadAuthorisedAssessmentClassIds,
  loadAuthorisedAssessmentStudentIds,
  assertCanTargetAssessmentClass,
  assertCanManageAssessment,
  canSeeAssessment,
  assertCanReadAssessment,
  assertCanEnterResultForPupil,
  assertCanReadStudentAcademic,
  assertCanManageReport,
  assertCanReadReport,
  snapshotAssessmentInclusions,
  parentUsersForStudents,
  notifyResultReleased,
  notifyReportPublished,
} from "./assessments-access.js";

export {
  PUBLIC_FORM_MAX_BODY_BYTES,
  PUBLIC_FORM_DRAFT_TTL_DAYS,
  PUBLIC_FORM_MAX_GUARDIANS,
  ADMISSIONS_UPLOAD_MAX_BYTES,
  sanitizePlainText,
  sanitizeHelperText,
  isSafeHttpUrl,
  safePrivacyNoticeUrl,
  normalizeFormSlug,
  normalizeCampaignCode,
  normalizeCustomFieldKey,
  publicFormKind,
  formTypeFromPublicKind,
  publicFormPath,
  publicFormEmbedPath,
  buildPublicFormUrl,
  buildEmbedCode,
  hashContinuationToken,
  createContinuationToken,
  hashClientIp,
  fieldDefinitionForCanonical,
  defaultFormTemplate,
  publicFormIsAccepting,
  validateFieldAnswer,
  validatePublicAnswers,
  fileAnswerDocumentId,
  mapAnswersToCanonical,
  computeCompleteness,
  declarationSnapshot,
  auditSafeFormAfter,
  isAdmissionsFormType,
  isAdmissionsFormStatus,
  isAdmissionsQuestionType,
  isAdmissionsCompletenessStatus,
  isCanonicalFieldKey,
  isAllowedAdmissionsUpload,
  canonicalTypeForKey,
  canonicalLabelForKey,
  type FormFieldDefinition,
  type FormSectionDefinition,
  type CanonicalSnapshot,
  type GuardianValue,
  type AddressValue,
} from "./admissions-forms.js";

export {
  MemoryRateLimiter,
  defaultPublicFormRateLimiter,
  DisabledCaptcha,
  defaultCaptcha,
  createCaptchaFromEnv,
  assertPublicFormPayloadSize,
  assertNotRateLimited,
  publicFormRateLimitKey,
  trustedClientIp,
  type RateLimitPort,
  type CaptchaPort,
} from "./public-forms-security.js";

export { qrSvg } from "./qr.js";

export {
  isAnnouncementStatus,
  isAnnouncementPriority,
  isCommunicationTargetType,
  isBroadcastTargetType,
  isCommunicationResourceKind,
  isSchoolEventStatus,
  isSchoolEventTypeKey,
  isCommunicationRelatedKind,
  isAnnouncementStatusTransitionAllowed,
  isEventStatusTransitionAllowed,
  effectiveAnnouncementStatus,
  isActiveAnnouncementStatus,
  announcementNeedsActivation,
  eventNeedsActivation,
  eventDatesValid,
  summariseAnnouncementReceipts,
  communicationNotificationBody,
  isStaffOnlyTargetType,
  targetIncludesParents,
  targetIncludesStudents,
  targetIncludesStaff,
  buildCommunicationResourceKey,
} from "./communications.js";

export {
  ANNOUNCEMENT_SCHOOL_READ_PERMISSIONS,
  ANNOUNCEMENT_MANAGE_PERMISSIONS,
  ANNOUNCEMENT_READ_PERMISSIONS,
  CALENDAR_SCHOOL_READ_PERMISSIONS,
  CALENDAR_MANAGE_PERMISSIONS,
  CALENDAR_READ_PERMISSIONS,
  canReadSchoolAnnouncements,
  canManageSchoolAnnouncements,
  canPublishAnnouncements,
  canBroadcastAnnouncements,
  canManageAssignedAnnouncements,
  canReadAnnouncementReceipts,
  canReadSchoolCalendar,
  canManageSchoolCalendar,
  canManageAssignedCalendar,
  assertCanTargetCommunication,
  resolveCommunicationAudience,
  snapshotAnnouncementRecipients,
  snapshotEventAudience,
  notifyAnnouncementPublished,
  notifyEventUpcoming,
  activateDueAnnouncements,
  activateDueEvents,
  assertCanReadStaffAnnouncement,
  assertCanManageStaffAnnouncement,
  announcementVisibleToAssignedStaff,
  assertCanReadStaffEvent,
  assertCanManageStaffEvent,
  eventVisibleToAssignedStaff,
  targetsAreStaffOnly,
  loadAnnouncementReceiptSummary,
  auditCommunication,
  type CommunicationTargetInput,
} from "./communications-access.js";

export {
  auditSafeDietaryAfter,
  auditSafeMedicationAfter,
  isDietaryRecordStatus,
  isDietaryRequirementType,
  isMedicationAdministrationResponsibility,
  isMedicationRecordStatus,
  isMedicationRoute,
  isParentConsentStatus,
  isPupilMedicalChangeKind,
  isPupilMedicalView,
  parentVisibleGranted,
  mapDietaryRecord,
  mapDietaryRevision,
  mapMedicationRecord,
  mapMedicationRevision,
  summariseActiveDietary,
  summariseActiveMedications,
  type DietaryRecordView,
  type DietaryRevisionView,
  type MedicationRecordView,
  type MedicationRevisionView,
} from "./additional-needs.js";

export {
  assertCanManagePupilAdditionalNeeds,
  canManageAdditionalNeeds,
  canReadFullAdditionalNeeds,
  canReadOperationalDietary,
  canReadOperationalMedications,
  canReadParentDietary,
  canReadParentMedications,
  resolveDietaryView,
  resolveMedicationView,
} from "./additional-needs-access.js";

export {
  isBehaviourIncidentStatus,
  isBehaviourSeverity,
  isBehaviourActionStatus,
  isPastoralConcernStatus,
  isPastoralPriority,
  isPastoralInterventionType,
  isSafeguardingConcernStatus,
  isSafeguardingChronologyEntryType,
  isPastoralRecordAttachmentParentKind,
  isIncidentStatusTransitionAllowed,
  isActionStatusTransitionAllowed,
  isPastoralStatusTransitionAllowed,
  isSafeguardingStatusTransitionAllowed,
  pastoralNotificationBody,
  behaviourNotificationBody,
  safeguardingNotificationBody,
  auditSafeBehaviourAfter,
  auditSafeSafeguardingAfter,
  buildBehaviourAttachmentKey,
  buildSafeguardingAttachmentKey,
} from "./behaviour.js";

export {
  BEHAVIOUR_SCHOOL_READ_PERMISSIONS,
  BEHAVIOUR_RECORD_PERMISSIONS,
  BEHAVIOUR_POSITIVE_RECORD_PERMISSIONS,
  PASTORAL_SCHOOL_READ_PERMISSIONS,
  SAFEGUARDING_ACCESS_PERMISSIONS,
  canReadSchoolBehaviour,
  canManageBehaviour,
  canRecordBehaviour,
  canReadAssignedBehaviour,
  canRecordPositiveBehaviour,
  canAccessBehaviour,
  canReadSchoolPastoral,
  canManagePastoral,
  canReadAssignedPastoral,
  canAccessPastoral,
  canReadSafeguarding,
  canRecordSafeguarding,
  canManageSafeguarding,
  canAssignSafeguarding,
  assertCanAccessSafeguarding,
  loadAuthorisedBehaviourStudentIds,
  loadAuthorisedPastoralStudentIds,
  assertCanReadStudentBehaviour,
  assertCanRecordStudentBehaviour,
  assertCanReadStudentPastoral,
  requireStudentInOrganisation,
  requireStaffUserInOrganisation,
  requireCategoryInOrganisation,
  requireClassInOrganisation,
  auditBehaviour,
  auditSafeguarding,
  notifyPastoralAssigned,
  notifySafeguardingAssigned,
  notifyFollowUpDue,
} from "./behaviour-access.js";

export {
  isSchoolDayPeriodType,
  isRoomLocationType,
  isTimetableLessonType,
  isTimetableTeacherRole,
  isTimetableExceptionType,
  isTimetableOccurrenceStatus,
  isIsoWeekday,
  isoWeekdayFromDate,
  addDays,
  eachDateInclusive,
  timesOverlap,
  dateWindowsOverlap,
  dateInRange,
  startOfIsoWeek,
  isoWeekRange,
  firstWeekdayOnOrAfter,
  formatUkLongDate,
  formatUkTimeRange,
  recurringLessonSavedMessage,
  weekdayLabel,
  occurrenceStatusFromException,
  inferAttendanceSessionKey,
} from "./timetable.js";

export {
  TIMETABLE_SCHOOL_READ_PERMISSIONS,
  TIMETABLE_READ_PERMISSIONS,
  TIMETABLE_MANAGE_PERMISSIONS,
  canReadSchoolTimetable,
  canManageSchoolTimetable,
  canManageSchoolDay,
  canReadAssignedTimetable,
  canReadRooms,
  canManageRooms,
  canReadCover,
  canManageCover,
  canReadOwnChildrenTimetable,
  canReadOwnTimetable,
  coveringClassIds,
  isCoveringClass,
  participatingClassIds,
  participatingEntryIds,
  permanentlyAssignedClassIds,
  coveredEntryIds,
  authorisedTimetableClassIds,
  assertCanReadClassTimetable,
  assertCanManageTimetable,
  requireOrgRow,
  loadSchoolClosureDates,
  loadTermWindows,
  dateIsSchoolDate,
  resolveTimetableOccurrences,
  firstTimetableOccurrence,
  resolveAttendanceRegisterTarget,
  loadStudentClassIdsAsOf,
  loadStudentClassMembershipsOverlapping,
  type ResolvedOccurrence,
  type OccurrenceTeacher,
} from "./timetable-access.js";

export {
  isSchoolActivityStatus,
  isSchoolActivityTypeKey,
  isSchoolActivityTargetType,
  isSchoolActivityStaffRole,
  isSchoolActivityOccurrenceKind,
  isSchoolActivityRegistrationStatus,
  isSchoolActivityAttendanceStatus,
  isSchoolActivityResponseValue,
  isSchoolActivityResponseChannel,
  isSchoolActivityRegistrationSource,
  isSchoolActivityDocumentVisibility,
  isActivityStatusTransitionAllowed,
  activityDatesValid,
  activityDeadlineValid,
  activityResponseWindowOpen,
  activityOpenForStaffChanges,
  activityVisibleOnPortal,
  activityDocumentVisibleToAudience,
  activityStaffSeesMedicalWindow,
  snapshotConsentWording,
  nextWaitingListPosition,
  allocateRegistrationStatus,
  activityNotificationBody,
  expandActivityOccurrences,
  parseActivityWeekdays,
  parseActivityIsoDate,
  summariseActivityResponses,
  availableSpaces,
  type ConsentClauseSnapshot,
  type ActivityCalendarOccurrence,
  type ActivitySafetySummary,
} from "./activities.js";

export {
  staffPersonaLabel,
  STAFF_PERSONA_LABELS,
  STAFF_ROLE_KEYS,
  isActiveNavHref,
  isNavSectionOpen,
  staffDashboardKind,
  statusTone,
  formatStatusLabel,
  hasAnyPermission,
  hasPermissionPrefix,
} from "@schoolapp/domain";

export {
  ACTIVITY_SCHOOL_READ_PERMISSIONS,
  ACTIVITY_MANAGE_PERMISSIONS,
  ACTIVITY_READ_PERMISSIONS,
  canReadSchoolActivities,
  canManageSchoolActivities,
  canManageAssignedActivities,
  canPublishActivities,
  canReadParticipants,
  canManageParticipants,
  canReadResponses,
  canManageResponses,
  canReadMedicalSummary,
  canReadActivityStaffNotes,
  isActivityStaff,
  loadActivityRow,
  assertCanReadStaffActivity,
  assertCanManageStaffActivity,
  assertCanPublishActivity,
  assertCanTargetActivity,
  replaceActivityTargets,
  snapshotActivityEligibility,
  loadConsentClauses,
  parentUsersForActivityPupils,
  guardianMayRespond,
  notifyActivityPublished,
  notifyActivityCancelled,
  lockActivityCapacity,
  upsertParticipant,
  recordActivityResponse,
  applyConsentDecision,
  maybePromoteNextWaitlisted,
  pupilIsEligible,
  auditActivity,
  listCalendarActivities,
  loadActivitySafetySummaries,
  type ActivityTargetInput,
} from "./activities-access.js";

export {
  isIsoCurrency,
  normalizeCurrency,
  assertSameCurrency,
  assertNonNegativeMinor,
  assertPositiveMinor,
  addMinor,
  subtractMinor,
  minMinor,
  maxMinor,
  outstandingMinor,
  netPaidMinor,
  currencyExponent,
  formatMoney,
  parseMajorToMinor,
  redactProviderReference,
  type Money,
} from "./money.js";

export {
  isSchoolChargeStatus,
  isSchoolChargeCategoryKey,
  isSchoolChargeSourceKind,
  isSchoolChargeAdjustmentKind,
  isSchoolPaymentTransactionStatus,
  isSchoolPaymentChannel,
  isSchoolPaymentProviderKey,
  isSchoolOfflinePaymentMethod,
  isSchoolPaymentRefundStatus,
  isSchoolPaymentSessionStatus,
  isSchoolActivityChargePolicy,
  isSchoolActivityPaymentStatus,
  chargeBalance,
  deriveChargeStatus,
  chargeIsPayable,
  dueUrgency,
  operationalPaymentStatus,
  shouldGenerateActivityCharge,
  shouldCancelActivityCharge,
  paymentNotificationBody,
  financeUserError,
  type ChargeBalance,
} from "./payments.js";

export {
  paymentConfigFromEnv,
  createPaymentProvider,
  FakePaymentProvider,
  StripePaymentProvider,
  signFakePaymentEvent,
  signFakeCheckoutToken,
  parseFakePaymentEvent,
  verifyStripeSignature,
  mapStripeEvent,
  safeProviderMetadata,
  type PaymentProvider,
  type PaymentRuntimeConfig,
  type ProviderEvent,
  type CreatePaymentSessionInput,
  type PaymentSessionResult,
} from "./payment-provider.js";

export {
  FINANCE_READ_PERMISSIONS,
  FINANCE_MANAGE_PERMISSIONS,
  canReadSchoolFinance,
  canManageCharges,
  canRecordOffline,
  canManageRefunds,
  canManageAdjustments,
  canReadFinanceReports,
  canReadOwnChildrenFinance,
  throwFinance,
  loadOrgCurrency,
  nextFinanceReference,
  loadCategoryId,
  lockCharge,
  loadChargeTotals,
  chargeBalanceFor,
  refreshChargeStatus,
  auditFinance,
  createCharge,
  issueCharge,
  cancelCharge,
  createBulkCharges,
  applyChargeAdjustment,
  recordOfflinePayment,
  createCheckoutSession,
  settleProviderEvent,
  requestRefund,
  applySucceededRefund,
  createReceipt,
  syncActivityCharge,
  loadOperationalPaymentStatus,
  resolveBulkStudentIds,
  assertParentFinanceAccess,
} from "./payments-access.js";

export {
  applyDiscounts,
  applyMidPeriodPolicy,
  arrearsBucket,
  asIsoDate,
  billingPeriodKey,
  compareSiblings,
  deriveInvoiceStatus,
  invoiceOutstandingMinor,
  isSchoolBillingFrequency,
  isSchoolCreditKind,
  isSchoolDiscountStackingMode,
  isSchoolInvoicePaymentMethod,
  isSchoolInvoiceStatus,
  orderSiblings,
  percentOfMinor,
  prorateMinor,
  splitAnnualIntoInstalments,
  type AppliedDiscount,
  type DiscountApplication,
  type DiscountCandidate,
  type SiblingSortInput,
} from "./tuition.js";

export {
  TUITION_READ_PERMISSIONS,
  applyOptionalPupilImportFinance,
  assertTuitionRead,
  canManageBillingRuns,
  canManageDiscounts,
  canManageFeeSchedules,
  canManageFinanceSettings,
  canManageInvoices,
  canReadTuition,
  confirmBillingRun,
  createDiscountRule,
  createFeeSchedule,
  createInvoiceCredit,
  createPupilConcession,
  createStaffChildLink,
  ensureBillingAccount,
  familyStudentIds,
  listArrears,
  listBillingAccounts,
  listBillingRuns,
  listDiscountRules,
  listFeeSchedules,
  listInvoices,
  listStaffChildLinks,
  loadAccountStatement,
  loadBillingAccount,
  loadBillingRun,
  loadFinanceSettings,
  loadInvoice,
  loadParentFinance,
  loadParentInvoice,
  loadParentStatement,
  loadPupilFeeProfile,
  loadTuitionDashboard,
  parentAuthorisedAccountIds,
  previewBillingRun,
  quotePupilTuition,
  recordInvoicePayment,
  reverseInvoicePayment,
  revokeStaffChildLink,
  updateDiscountRule,
  updateFeeSchedule,
  updateFinanceSettings,
  upsertPupilFeeProfile,
  voidInvoice,
} from "./tuition-access.js";

export {
  isMessageConversationType,
  isMessageConversationStatus,
  isMessageParticipantKind,
  isMessageType,
  isMessageRelatedDomain,
  isMessageParentContactPoint,
  sanitizeMessageSubject,
  sanitizeMessageBody,
  messagePreview,
  displayMessageBody,
  conversationAllowsReplies,
  messagingNotificationBody,
  relatedDomainLabel,
  MESSAGE_BODY_MAX,
  MESSAGE_SUBJECT_MAX,
  MESSAGE_PREVIEW_MAX,
  MESSAGE_REDACTED_BODY,
  PARENT_FACING_CONVERSATION_TYPES,
} from "./messaging.js";

export {
  messagingRateLimiter,
  MESSAGING_STAFF_READ_PERMISSIONS,
  canReadSchoolMessaging,
  canManageMessaging,
  canModerateMessaging,
  canCreateSchoolMessaging,
  canCreateAssignedMessaging,
  canUseStaffInternal,
  canUseAdmissionsMessaging,
  hasAnyStaffMessagingAccess,
  assertMessagingRateLimit,
  auditMessaging,
  evaluateConversationAccess,
  requireConversationAccess,
  loadConversationRow,
  assertCanAccessMessageAttachment,
  listAssignedClassTeachers,
  listParentContactPoints,
  listPupilMessageRecipients,
  listConversations,
  countUnreadConversations,
  countUnreadMessages,
  loadConversationDetail,
  createStaffConversation,
  createParentConversation,
  sendConversationMessage,
  listConversationMessages,
  markConversationRead,
  closeConversation,
  reopenConversation,
  archiveOwnConversation,
  redactMessage,
  attachMessageFile,
  listPupilContactHistory,
} from "./messaging-access.js";

export { generatePermanentUpn, isValidPermanentUpn, normaliseUpn, validateUpn, upnCheckLetter } from "./upn.js";

export {
  NoopMailProvider,
  OutboxMailProvider,
  assertNoPasswordInMail,
  parentInviteMail,
  passwordResetMail,
  staffInviteMail,
  studentActivationMail,
  type MailMessage,
  type MailProvider,
} from "./mail.js";

export {
  evaluateReadiness,
  presentSchoolOnboarding,
  PASSWORD_RESET_NEUTRAL_MESSAGE,
  type ReadinessCounts,
  type ReadinessViewItem,
  type SchoolOnboardingView,
} from "./onboarding.js";

export {
  IMPORT_TEMPLATES,
  csvFormulaSafe,
  importTemplateCsv,
  parseCsvText,
  rowToRecord,
  validateGuardianImportRow,
  validatePupilImportRow,
  validateStaffImportRow,
  type ImportIssue,
  type ImportRowPreview,
} from "./imports.js";

export {
  compareIsoDates,
  dateCountsTowardAttendance,
  dateInInclusiveRange,
  isCurrentPupil,
  isFormerPupil,
  isOnRollOnDate,
  leftDuringPeriod,
  onRollWindow,
  wasAdmittedDuringPeriod,
  type OnRollPupil,
} from "./on-roll.js";

export {
  DEFAULT_STATUTORY_CODES,
  buildStatutoryCodeLookup,
  defaultStatutoryCodeLookup,
  isStatutoryCode,
  statutoryCodeName,
  type StatutoryCode,
  type StatutoryCodeLookup,
} from "./statutory-codes.js";

export {
  CENSUS_SNAPSHOT_SCHEMA_VERSION,
  auditSafeStatutoryAfter,
  censusIsImmutable,
  censusMayExport,
  censusMayFinalise,
  censusMayRegenerate,
  countIssues,
  fsmEligibleOnDate,
  isCensusRunStatus,
  isCensusType,
  isDataExportFormat,
  isDataExportKind,
  isLookedAfterStatus,
  mapOperationalSendToStatutory,
  splitLegalName,
  validateEstablishmentNumber,
  validateLocalAuthorityNumber,
  validateUrn,
  type FsmPeriod,
  type PupilStatutoryRecord,
  type SchoolStatutoryRecord,
  type StatutoryIssue,
} from "./statutory.js";

export { validateStatutory, validateStatutoryPupil, validateStatutorySchool } from "./statutory-validation.js";

export {
  ADMISSIONS_ENROLMENT_COLUMNS,
  ATTENDANCE_SUMMARY_COLUMNS,
  CENSUS_SNAPSHOT_COLUMNS,
  PUPIL_ROLL_COLUMNS,
  SEND_EXPORT_COLUMNS,
  censusXmlPreview,
  csvCell,
  preventCsvInjection,
  toCsv,
  xmlEscape,
} from "./statutory-export.js";

export {
  DEFAULT_STATUTORY_ATTENDANCE_MAP,
  groupAttendanceSummaries,
  mapAttendanceToStatutoryCategory,
  summariseStatutoryAttendance,
} from "./statutory-attendance.js";

export {
  REPORT_EXPORT_PERMISSIONS,
  STATUTORY_PUPIL_READ_PERMISSIONS,
  STATUTORY_READ_PERMISSIONS,
  assertCanCreateCensus,
  assertCanExportCensus,
  assertCanFinaliseCensus,
  assertCanManagePupilStatutory,
  assertCanManageStatutory,
  assertCanReadPupilStatutory,
  assertCanReadSendReport,
  assertCanReadStatutory,
  assertCanValidateStatutory,
  canCreateCensus,
  canCreateReportExport,
  canExportCensus,
  canFinaliseCensus,
  canManagePupilStatutory,
  canManageStatutory,
  canReadAdmissionsReport,
  canReadAttendanceReport,
  canReadPupilRollReport,
  canReadPupilStatutory,
  canReadSendReport,
  canReadStatutory,
  canValidateStatutory,
} from "./statutory-access.js";

export {
  loadLiveStatutoryPupils,
  loadSchoolStatutoryRecord,
  loadSnapshotPupils,
  loadSnapshotSchool,
  loadStatutoryCodeLookup,
  pupilToSnapshotRow,
} from "./statutory-data.js";

export {
  ACHIEVEMENT_CRITERIA_TYPES,
  COMPETITION_SCORING_MODELS,
  COMPETITION_STATUSES,
  COMPETITION_TYPES,
  DEFAULT_ENGAGEMENT_SETTINGS,
  FUTURE_AI_ACTIVITY_WORKFLOW,
  LEADERBOARD_DISPLAY_POLICIES,
  PRACTICE_ACTIVITY_TYPES,
  PRACTICE_ITEM_TYPES,
  achievementMeetsCriteria,
  effectiveDisplayPolicy,
  firstGivenName,
  formatLeaderboardDisplayName,
  isCompletedByThreshold,
  isCompetitionStatusTransitionAllowed,
  leaderboardPrivacy,
  parsePracticeItems,
  practiceActivityAllowed,
  resolveEngagementPolicy,
  scorePracticeAttempt,
  scorePracticeItem,
  stripAnswerKey,
  surnameInitial,
  type AchievementCriteriaType,
  type AchievementProgress,
  type CompetitionScoringModel,
  type CompetitionStatus,
  type CompetitionType,
  type EffectiveEngagementPolicy,
  type EngagementSettings,
  type LeaderboardDisplayPolicy,
  type LeaderboardPrivacy,
  type PracticeActivityType,
  type PracticeChoice,
  type PracticeClientItem,
  type PracticeCorrectAnswer,
  type PracticeItem,
  type PracticeItemType,
  type YearGroupEngagementPolicy,
} from "./engagement.js";

export {
  canAwardAssignedRewards,
  canAwardSchoolRewards,
  canManageAchievements,
  canManageAssignedPractice,
  canManageCompetitions,
  canManageEngagementSettings,
  canManageRewards,
  canManageSchoolCompetitions,
  canManageSchoolPractice,
  canReadEngagementSettings,
  canReadSchoolAchievements,
  canReadSchoolCompetitions,
  canReadSchoolPractice,
  canReadSchoolRewards,
  ensureEngagementDefaults,
  loadAuthorisedEngagementStudentIds,
  loadEffectiveEngagementPolicy,
  loadEngagementSettings,
  loadPupilHouseId,
  loadPupilYearGroupId,
  loadYearGroupEngagementPolicy,
  requireCurrentEnrolment,
  assertCanAccessEngagementStudent,
  assertCanTargetPractice,
} from "./engagement-access.js";
