export {
  canReadStudentProfile,
  canReadRestrictedContact,
  assignedStudentIds,
  isAssignedToClass,
  assignedClassIds,
  classStudentIdsAsOf,
  guardianChildIds,
  canListAllStudents,
  canManageStudents,
  canManageAcademicStructure,
  canReadAcademicStructure,
} from "./students-access.js";

export { assertPermission, assertAnyPermission, notFound } from "./permissions.js";

export {
  ADMISSIONS_READ_PERMISSIONS,
  canReadAdmissions,
  canManageEnquiries,
  canManageApplications,
  canManageOffers,
  canDecideAdmissions,
  canConvertAdmissions,
  canReadAdmissionsForms,
  canManageAdmissionsForms,
  canReadAdmissionsCampaigns,
  canManageAdmissionsCampaigns,
  canReadPublicSubmissions,
  allowedApplicationTransitions,
  isApplicationStatusTransitionAllowed,
  transitionRequiresDecide,
  assertApplicationStatusTransition,
  createInboxNotification,
  auditAdmissions,
} from "./admissions.js";

export { AppError, pgErrorToAppError } from "./errors.js";

export {
  normalizePlatformDomain,
  parseHostHeader,
  selectRequestHost,
  firstForwardedHost,
  classifyHostname,
  schoolPublicHostname,
  originForHostname,
  formatHostname,
  type ParsedHost,
  type HostClassification,
} from "./hostname.js";

export {
  bindOrganisationHint,
  headerMatchesHostSlug,
  type BoundOrganisation,
} from "./tenancy.js";

export {
  writeAudit,
  currentAcademicYear,
  endDatedRow,
  isoDate,
} from "./academic.js";

export {
  comingLater,
  PORTAL_STUDENT_SQL,
  mapPortalStudent,
  portalChildSummary,
  loadSchool,
  loadPortalStudentsByIds,
  loadPortalStudent,
  loadOwnStudentProfile,
  requireLinkedChild,
  loadViewerGuardianship,
  PARENT_CHILD_SECTIONS,
  STUDENT_DASHBOARD_SECTIONS,
} from "./portal.js";

export {
  mapNotification,
  listInboxNotifications,
  countUnreadNotifications,
  markNotificationRead,
} from "./notifications.js";

export {
  isAttendanceCategory,
  roundAttendancePercentage,
  attendancePercentage,
  summariseAttendanceMarks,
  emptyAttendanceSummary,
  type AttendanceSummary,
} from "./attendance.js";

export {
  resolveStudentPortalAccess,
  yearGroupPortalEffective,
  type StudentPortalPolicyInput,
  type StudentPortalDecision,
} from "./student-portal.js";

export {
  ATTENDANCE_SCHOOL_READ_PERMISSIONS,
  ATTENDANCE_REGISTER_PERMISSIONS,
  canReadSchoolAttendance,
  canManageSchoolAttendance,
  canCorrectAttendance,
  canManageAssignedAttendance,
  canManageAttendanceConfig,
  canReadOwnChildrenAttendance,
  canReadOwnAttendance,
  assertCanAccessRegister,
  assertCanReadStudentAttendance,
  loadStudentPortalDecision,
  requireStudentPortalEnabled,
  studentDocumentVisibleToAudience,
  buildStudentDocumentKey,
} from "./attendance-access.js";

export {
  isLearningAssignmentStatus,
  isLearningSubmissionStatus,
  isLearningTargetType,
  isLearningResourceKind,
  isLearningWorkTypeKey,
  isLearningStudentBucket,
  isAssignmentStatusTransitionAllowed,
  isSubmissionStatusTransitionAllowed,
  pupilCanSubmitFrom,
  pupilCanSaveDraftFrom,
  pupilCanWriteOnAssignment,
  isAllowedLearningUrl,
  isScoreInRange,
  summariseLearningProgress,
  isLearningVisibleToPupil,
  studentLearningBuckets,
  parentLearningStatus,
  learningNotificationBody,
  type LearningProgressCounts,
  type StudentLearningVisibilityInput,
} from "./learning.js";

export {
  LMS_SCHOOL_READ_PERMISSIONS,
  LMS_ASSIGN_PERMISSIONS,
  LMS_READ_WORK_PERMISSIONS,
  LMS_READ_SUBMISSION_PERMISSIONS,
  LMS_MARK_PERMISSIONS,
  canManageSchoolLearning,
  canReadSchoolLearning,
  canManageAssignedLearning,
  canReadAssignedLearning,
  canMarkSchoolLearning,
  canMarkAssignedLearning,
  canReadOwnChildrenLearning,
  canReadOwnLearning,
  assertCanManageLearningWork,
  assertCanAccessClassForLearning,
  assertCanTargetClass,
  assertCanTargetStudent,
  assertCanTargetYearGroup,
  loadAuthorisedLearningClassIds,
  loadAuthorisedLearningStudentIds,
  assertCanReadAssignment,
  assertCanManageAssignment,
  assertCanReadOrMarkSubmission,
  canSeeLearningRecipient,
  resolveTargetRecipients,
  snapshotAssignmentRecipients,
  notifyLearningAssigned,
  notifyLearningFeedback,
  buildLearningResourceKey,
  buildSubmissionAttachmentKey,
} from "./learning-access.js";

export {
  isFormalAssessmentStatus,
  isFormalAssessmentTypeKey,
  isGradeSchemeKind,
  isResultReviewStatus,
  isReportingPeriodStatus,
  isAcademicReportStatus,
  isAssessmentStatusTransitionAllowed,
  isReportStatusTransitionAllowed,
  canEnterResultsOnAssessment,
  isFormalResultVisibleToAudience,
  isScoreWithinMaximum,
  computePercentage,
  summariseSubjectProgress,
  summariseAssessmentResults,
  academicNotificationBody,
  type ProgressPoint,
  type SubjectProgressSummary,
} from "./assessments.js";

export {
  ASSESSMENT_SCHOOL_READ_PERMISSIONS,
  ASSESSMENT_MANAGE_PERMISSIONS,
  ASSESSMENT_READ_PERMISSIONS,
  RESULT_SCHOOL_READ_PERMISSIONS,
  RESULT_ENTER_PERMISSIONS,
  RESULT_READ_PERMISSIONS,
  REPORT_SCHOOL_READ_PERMISSIONS,
  REPORT_MANAGE_PERMISSIONS,
  REPORT_READ_PERMISSIONS,
  canReadSchoolAssessments,
  canManageSchoolAssessments,
  canReadSchoolResults,
  canEnterSchoolResults,
  canReviewResults,
  canPublishResults,
  canReadSchoolReports,
  canManageSchoolReports,
  canReviewReports,
  canPublishReports,
  loadAuthorisedAssessmentClassIds,
  loadAuthorisedAssessmentStudentIds,
  assertCanTargetAssessmentClass,
  assertCanManageAssessment,
  canSeeAssessment,
  assertCanReadAssessment,
  assertCanEnterResultForPupil,
  assertCanReadStudentAcademic,
  assertCanManageReport,
  assertCanReadReport,
  snapshotAssessmentInclusions,
  parentUsersForStudents,
  notifyResultReleased,
  notifyReportPublished,
} from "./assessments-access.js";

export {
  PUBLIC_FORM_MAX_BODY_BYTES,
  PUBLIC_FORM_DRAFT_TTL_DAYS,
  PUBLIC_FORM_MAX_GUARDIANS,
  ADMISSIONS_UPLOAD_MAX_BYTES,
  sanitizePlainText,
  sanitizeHelperText,
  isSafeHttpUrl,
  safePrivacyNoticeUrl,
  normalizeFormSlug,
  normalizeCampaignCode,
  normalizeCustomFieldKey,
  publicFormKind,
  formTypeFromPublicKind,
  publicFormPath,
  publicFormEmbedPath,
  buildPublicFormUrl,
  buildEmbedCode,
  hashContinuationToken,
  createContinuationToken,
  hashClientIp,
  fieldDefinitionForCanonical,
  defaultFormTemplate,
  publicFormIsAccepting,
  validateFieldAnswer,
  validatePublicAnswers,
  mapAnswersToCanonical,
  computeCompleteness,
  declarationSnapshot,
  auditSafeFormAfter,
  isAdmissionsFormType,
  isAdmissionsFormStatus,
  isAdmissionsQuestionType,
  isAdmissionsCompletenessStatus,
  isCanonicalFieldKey,
  isAllowedAdmissionsUpload,
  canonicalTypeForKey,
  canonicalLabelForKey,
  type FormFieldDefinition,
  type FormSectionDefinition,
  type CanonicalSnapshot,
  type GuardianValue,
  type AddressValue,
} from "./admissions-forms.js";

export {
  MemoryRateLimiter,
  defaultPublicFormRateLimiter,
  DisabledCaptcha,
  defaultCaptcha,
  createCaptchaFromEnv,
  assertPublicFormPayloadSize,
  assertNotRateLimited,
  publicFormRateLimitKey,
  trustedClientIp,
  type RateLimitPort,
  type CaptchaPort,
} from "./public-forms-security.js";

export { qrSvg } from "./qr.js";

export {
  isAnnouncementStatus,
  isAnnouncementPriority,
  isCommunicationTargetType,
  isBroadcastTargetType,
  isCommunicationResourceKind,
  isSchoolEventStatus,
  isSchoolEventTypeKey,
  isCommunicationRelatedKind,
  isAnnouncementStatusTransitionAllowed,
  isEventStatusTransitionAllowed,
  effectiveAnnouncementStatus,
  isActiveAnnouncementStatus,
  announcementNeedsActivation,
  eventNeedsActivation,
  eventDatesValid,
  summariseAnnouncementReceipts,
  communicationNotificationBody,
  isStaffOnlyTargetType,
  targetIncludesParents,
  targetIncludesStudents,
  targetIncludesStaff,
  buildCommunicationResourceKey,
} from "./communications.js";

export {
  ANNOUNCEMENT_SCHOOL_READ_PERMISSIONS,
  ANNOUNCEMENT_MANAGE_PERMISSIONS,
  ANNOUNCEMENT_READ_PERMISSIONS,
  CALENDAR_SCHOOL_READ_PERMISSIONS,
  CALENDAR_MANAGE_PERMISSIONS,
  CALENDAR_READ_PERMISSIONS,
  canReadSchoolAnnouncements,
  canManageSchoolAnnouncements,
  canPublishAnnouncements,
  canBroadcastAnnouncements,
  canManageAssignedAnnouncements,
  canReadAnnouncementReceipts,
  canReadSchoolCalendar,
  canManageSchoolCalendar,
  canManageAssignedCalendar,
  assertCanTargetCommunication,
  resolveCommunicationAudience,
  snapshotAnnouncementRecipients,
  snapshotEventAudience,
  notifyAnnouncementPublished,
  notifyEventUpcoming,
  activateDueAnnouncements,
  activateDueEvents,
  assertCanReadStaffAnnouncement,
  assertCanManageStaffAnnouncement,
  announcementVisibleToAssignedStaff,
  assertCanReadStaffEvent,
  assertCanManageStaffEvent,
  eventVisibleToAssignedStaff,
  targetsAreStaffOnly,
  loadAnnouncementReceiptSummary,
  auditCommunication,
  type CommunicationTargetInput,
} from "./communications-access.js";
